name: squares_simple
description: A barebones example of how to use Squares.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bishop: ^1.2.9
  cupertino_icons: ^1.0.2
  squares:
      path: ../../
  square_bishop: ^0.2.13

dependency_overrides:
  squares:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
