name: squares
description: A flexible chessboard widget for Flutter. Visually customisable, with support for many chess variants.
version: 0.4.0
homepage: https://github.com/alexobviously/squares

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/piece_sets/merida/