name: squares
description: A flexible chessboard widget for Flutter. Visually customisable, with support for many chess variants.
version: 1.1.0
repository: https://github.com/alexobviously/squares

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  badges: ^2.0.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  assets:
    - lib/backgrounds/
    - lib/piece_sets/merida/
    - lib/piece_sets/xiangqi/
    - lib/piece_sets/xiangqi_icon/