name: squares
description: A flexible chessboard widget for Flutter
version: 0.2.0
homepage: https://github.com/alexobviously/squares

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/piece_sets/merida/