name: squares_complex
description: Squares example

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  bishop: ^1.4.0
  badges: ^3.0.2
  bloc: ^8.1.2
  dots_indicator: ^2.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  material_design_icons_flutter: ^7.0.7296
  squares:
    path: ../../
  square_bishop: ^0.2.16

dependency_overrides:
  squares:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/kaneo/