name: squares_complex
description: Squares example

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  bishop: ^1.0.0
  badges: ^3.0.2
  bloc: ^7.0.0
  dots_indicator: ^2.0.0
  equatable: ^2.0.5
  flutter_bloc: ^7.1.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.0.0
  google_fonts: ^3.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  squares:
    path: ../../
  square_bishop: ^0.2.9

dependency_overrides:
  squares:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/kaneo/